### ISSUE TITLE
!!! reaction times needs review

### ISSUE THREAD

**Issue by marcobarilari** [CerenB/ERPs_AuditoryMotion#14]
I tried to give a response at each trial and the RT are incremental across the experiment.

This:
            'responseTime = secs - experimentStartTime;'

should be changed with

            'StartResponse= GetSecs(); %right before the while loop which take the response
            [...]
            responseTime = secs - StartResponse;'

LMK

**Comment by CerenB** [comment]
It'd be better if you do not make any changes in the main script now. We
have been making changes for the sound card and all your changes will be
difficult to track down.
