### ISSUE TITLE
2 input sounds are not tracked

### ISSUE THREAD

**Issue by CerenB** [CerenB/ERPs_AuditoryMotion#8]
How can I ask Git/GitKraken/... to track something (seems to be) not tracked? 
e.g. stimuli > test > static.wav 
stimuli > test > static_T.wav 
are not being tracked.

**Comment by marcobarilari** [comment]
That is strange, you usually tell git to not track something via the gitignore file. We'll take a look later.

**Comment by CerenB** [comment]
Yes and no. We solved that problem with Remi yesterday. Probably you have
an old version - not sure why :)

But this is not a problem because stimulus input will change. It'll be
different files. Soon!
